### ISSUE TITLE
Auto Keyboard input

### ISSUE THREAD

**Issue by Lukas-Batema** [KittyPBoxx/GBAXG#9] opened 2023-11-19 05:44 UTC
When in most dialogue boxes, in battles, and in select menu, it automatically goes very quickly through text and hinders battling. It doesn't start doing it until I reach the "Mum" character when you just start off in Pallet town. It usually quickly closes the menu, but the timing varies slightly between each attempt, even on the same interaction in different attempts.

EDIT: Although I'm not sure if this fixes it, the auto text patch was on, but it seems to be backing out instead of advancing for me, so that could still be bugged. 

EDIT II: It still does this after refreshing with CTRL + R, after clearing stored roms, then I refreshed, then deselected the auto text patch, then loaded the roms back in from my FS, then starting game, then running through a few seeds until I feel like randomising the warps, before even starting actual gameplay, for more pseudo-randomness, then starting gameplay, up to that same point. This is very annoying and hinders gameplay greatly.

**Comment by KittyPBoxx** [comment] 2023-11-19 15:14
If I understand correctly you're experiencing repeat inputs/ inputs you're not doing?

This could be a keybind problem. You could try going to the 'Controls' tab and scroll down to reset keybinds. Refreshing/clearing roms e.t.c doesn't clear  keybind data.

You can have keybinds for A,  'Alt A', 'Turbo A', B, 'Alt B', 'Turbo B'.
The alt bindings are just for allowing the inputs from two separate buttons. Turbo repeatedly clicks a button.
It's also possible to bind 1 key to multiple inputs so that can cause issues.

**Comment by Lukas-Batema** [comment] 2023-11-19 20:10
For the first one, I never changed any of the controls, would it be a problem in the default controls? For the second one, I try that, and it still skipped and sped through dialogue. For the third, it's a first time download of chrome, because I always use Firefox, and read that Firefox may be buggy, so I'm not sure what Chrome would have that breaks it on first time installation.

**Comment by KittyPBoxx** [comment] 2023-11-20 22:13
Just to clarify the bottom section was just an explanation of how to manually clear the generated config (as hard refresh will still leave data). Firefox should work fine it just uses more resources to run so is more likely to lag on slower pcs.

---

If you have not set the controls before then there should not be an issue although it might be worth checking what the current keybinds are.  

I don't know if any of the following apply to you but I've had some reports of issues when:
1. The instant text option in UPR is used (if it is used the built in instant text patch must be disabled and a bios must be used)
2. Certain controllers (e.g mayflash adapters with GC controllers) are plugged into the system
3. using hotkeys F13-F24 (these trigger unexpected inputs in the emulator) 

---

I'm still not entirely sure what the problem you're facing is (if the text is too fast? or if it's clicking through too quickly)? 
If you should share a video of the issue/doing the setup that might clear things up. I've attached a video of how the setup is supposed to work without instant text where it appears to be working fine for me.

[gbaxg_slowtext_setup.webm](https://github.com/KittyPBoxx/GBAXG/assets/89883734/df0adbc3-94a2-495d-99ed-d9630a831cf8)

**Comment by Lukas-Batema** [comment] 2023-11-20 22:36
https://github.com/KittyPBoxx/GBAXG/assets/55695493/c0ae9eab-9164-462c-95e1-fba5029de4f8

Here the text is auto scrolling when I talk to the player's mum, and I just can't open the menu. I am using a keyboard that has macros, but all are not set to anything. I am not using the UPR, and have the instant text off, it always seems to re-enable it though after a refresh of the page or anything, sometimes even starting the game.

**Comment by KittyPBoxx** [comment] 2023-11-20 23:32
Ok, I think I've managed to reproduce your issue. It looks like holding down the turbo key on a keyboard gets the autofire stuck (although on a gamepad it seems to work fine).  

A and B are mapped to the keyboard keys 'K' and 'L' by default. The turbo keys are 'N' and 'M'. But holding down the 'M' key for 2-3 seconds the trigger b button gets stuck on repeat. This seems like the issue you're having. Can you confirm if this is what's happening?

I'll have to figure out why this happens. For now if you run the following commands in the dev console before starting the game that should disable the turbo buttons getting switched on.

'
GBAXG.commandExecutor._commands.set("TurboAKeyDown", e => {})
GBAXG.commandExecutor._commands.set("TurboBKeyDown", e => {})
'

**Comment by Lukas-Batema** [comment] 2023-11-21 00:14
Yes, that is exactly what is happening. I thought the M key was regular B, but I do know I was using B and K for that lol. I wasn't holding it down, more spamming it at times.

**Comment by KittyPBoxx** [comment] 2023-11-30 04:42
This issue was caused by how the auto fire interacted with the keyboard repeat delay. It should be fixed in the latest release. A hard refresh may be required for the new changes to take effect.  

Closing this as fixed.

**Closed by KittyPBoxx** 2023-11-30 04:42 UTC
